[package]
name = "zefiro"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "zefiro-cli",
    "zefiro-pipeline-engine",
    "zefiro-pipeline-engine/zefiro-cwl-parser",
    "zefiro-pipeline-engine/zefiro-cwl-js-exec",
    "zefiro-ui"
]